### PR TITLE
Cheatsheets for CM1015 Computational Mathematics 

### PR DESCRIPTION
**Pull request by lamafab**
Hello

I'm currently working on a collection of cheatsheets, meant to be useful for studying. Preview:

* [Number bases](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_number_bases.pdf)
* [Sequences and Series](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_sequence_series.pdf)
* [Modular Arithmetic](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_modular_arithmetic.pdf)
* [Trigonometry](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_trigonometry.pdf)
* [Graphs of Functions & Kinematics](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_graphs_functions_kinematics.pdf)
* [Trigonometrical Functions & Identities](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_trigonometrical_functions_identities.pdf)
* [Exponential & Logarithm Functions](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_exponential_logarithm_funcions.pdf)
* [Gradients of Curves & Differentiation](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_gradients_curves_differentiation.pdf)
* [Vectors](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_vectors.pdf)
* [Matrices](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_matrices.pdf)
* [Statistics](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_statistics.pdf)
* [Probability & Combinatorics](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_probability_combinatorics.pdf)

Do note that those are currently and actively being worked on and might contain mistakes or be incomplete. I will go over everything again and - assuming you're interested in merging this - will ping you when I think it's ready, _probably_ around the mid-terms. Any feedback/criticism is welcome. More topics are coming in the future, the goal is to cover all relevant topics of that module.

### CODE REVIEW

**Comment by Caroline-Chiu** [comment]
****

**Comment by ironoa** [comment]
Hey Fabio, just a suggestion.

Regarding [Graphs of Functions & Kinematics](https://github.com/lamafab/notes/blob/fabio-lama-notes/level-4/computational-mathematics/student-notes/fabio-lama/cheatsheet_graphs_functions_kinematics.png), specifically the Kinematics section:

I found really handy to think in terms of derivatives and integrals. So, rather than remembering all the formulas, you can start from the Fundamental law of Dynamics F=ma to deduce the position law:

a -> integral over time -> v -> integral over time -> r

a = constant in your case

v = ∫a dt = at + vo

r = ∫v dt = 1/2 at^2 + vot + ro

The vice versa is also valid:

r -> derivative with respect of time -> v -> derivative with respect of time -> a

**Comment by lamafab** [comment]
@sglavoie @ankush This PR is ready to be merged, thanks for the patience :)

**Review by sglavoie — APPROVED** [review]
Thank you @lamafab, this is awesome! 😎

**Pull request merged**
