### PR TITLE
feat: add dadt single page notes

### PR DESCRIPTION
**Pull request by claytonchew**
Adding my DADT single page notes.

### CODE REVIEW

**Comment by claytonchew** [comment]
@sglavoie are you looking into this?

**Comment by sglavoie** [comment]
No.

**Comment by claytonchew** [comment]
> No.

@sglavoie Ok... This PR is ready for your review. (same for #35)

Do have a look if you have the time. Would appreciate if this gets merged in as I was getting DMs in slack asking where's the note and some suggestions. Best to have these notes being improved upon and/or made available by others. Thanks.

**Comment by sglavoie** [comment]
Sorry, didn't see the previous message until now (not following these repos nor Slack). That clearly looks clean. If you know someone at UoL who might want to take a look at these repositories, you're welcome to recommend and I'll share access.

**Comment by claytonchew** [comment]
@sglavoie I may be able to help maintain the repository if you don't mind, but I'm already in my final session with UoL. Perhaps I can ask around to see who might can volunteer / be suitable to help maintain the repos forward. Let me know.

**Comment by bradatkinson96** [comment]
I wouldn't mind volunteering to help in any way. Let me know if I could be
any help. I'm starting my first year

**Comment by sglavoie** [comment]
Thank you @claytonchew! Do let me know if you still want access, but since you're on your way out, I would guess you will have other things to tackle. 🙂 

@BradAtkinCode96, while these repositories are not a highly technical space right now, it looks like it would align well with your current aspirations, especially as you are starting out the degree... and of course you can get involved in any way you wish that would benefit your own path. May it be reviewing pull requests or issues (always good to do!), participating in discussions, writing more Python scripts or setting up GitHub Actions to automate more stuff (as I see you're learning Python), transforming the REPL into an actual web application to gain concrete experience and make the information easier to find, etc. And obviously, that would depend on your availability, there's no obligation whatsoever, though getting one's hands dirty into some coding projects is always a good idea when starting out.

Let me know what you think, and I'll be sure to get back to you!

**Comment by claytonchew** [comment]
> Thank you @claytonchew! Do let me know if you still want access, but since you're on your way out, I would guess you will have other things to tackle. 🙂

@sglavoie Sure, since you asked, I'd be happy to help around here. I can start by looking into Issues or you happened to have something on your mind that needs improving, i.e. automation, scripts, etc. let me know, I'll look into it. You can also reach me over at t [dot] me [slash] claytonchew.

**Comment by sglavoie** [comment]
Hey @claytonchew, I sent you an invitation to become a maintainer. I leave the good judgement up to you: I am not aware of what is going on at UoL, what has been requested by students, what needs more attention, etc. I trust that you will do the best thing given your availability. Welcome aboard 😄.

**Comment by bradatkinson96** [comment]
@sglavoie Hey Sebastion. I would like to help out with the REPL pull requests and just generally tidying up the Repository for first year students. Please let me know if I'd be able to do that! 

Sorry for getting back to you so late on this, got carried away by the term.

**Comment by sglavoie** [comment]
@BradAtkinCode96 no problem! Invitation sent. 👍

**Pull request merged**
